// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/career-mate-navigation/Current.tsx": () => import("../components/mockups/career-mate-navigation/Current.tsx"),
  "./components/mockups/career-mate-navigation/SimplifiedPipeline.tsx": () => import("../components/mockups/career-mate-navigation/SimplifiedPipeline.tsx")
};
